services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      # Переопределяем для контейнера
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      PDF_DIR: /app/var/pdf
      UPLOADS_DIR: /app/var/uploads
      # В проде можно раскомментировать:
      # NODE_ENV: production
      # CLIENT_ORIGIN: "http://YOUR_PUBLIC_IP_OR_DOMAIN"
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - pdf_data:/app/var/pdf
      - uploads_data:/app/var/uploads

volumes:
  db_data:
  pdf_data:
  uploads_data: